
function install_hack() {
    TMP_="$1"
    KINDLE_="$2"
    FUNC="$3"

    mkdir "$TMP_" 2>/dev/null
    mount_fct "mount" 2>/dev/null
    extract "$KINDLE_" "$TMP_"


    FIRMWARE=$(tree -fil "$TMP_" | grep "$INSTALL" | grep $(cat files/config/versions| grep "$KVERSION" | cut -d '|' -f1))
    print_ok "Firmware found: $FIRMWARE" 1
    cp "$FIRMWARE" "$MNT"

    $FUNC

    print_help "update"
    rm -rf "$TMP_"
    mount_fct "unmount"
}
