
function screensaver_install() {
    print_ok "Screensaver hack installed" 1

    mkdir "$MNT"/linkss 2>/dev/null
    echo -n "    Do you wish to randomize your screensavers ? [Y/n] "
    read YN
    if [ "$YN" != "n" ]; then touch "$MNT"/linkss/random; fi
    echo -n "    Do you wish to shuffle your screensavers ? [Y/n] "
    read YN
    if [ "$YN" != "n" ]; then touch "$MNT"/linkss/shuffle; fi

    print_ok "Move your custom screensavers to $MNT/linkss/screensavers" 1
}